//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectRequestsFooditem
    {
        public int CollectRequestsFoodItemId { get; set; }
        public int RequestId { get; set; }
        public string ItemName { get; set; }
        public int Quantity { get; set; }
        public string ExpiryDate { get; set; }
        public string Description { get; set; }
    
        public virtual CollectRequest CollectRequest { get; set; }
    }
}
